# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/compact_index/all/compact_index.rbi
#
# compact_index-0.11.0
class CompactIndex::Gem < Struct
  def <=>(other); end
  def name; end
  def name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def versions; end
  def versions=(_); end
end
class CompactIndex::GemVersion < Struct
  def <=>(other); end
  def checksum; end
  def checksum=(_); end
  def dependencies; end
  def dependencies=(_); end
  def deps_line; end
  def info_checksum; end
  def info_checksum=(_); end
  def number; end
  def number=(_); end
  def number_and_platform; end
  def platform; end
  def platform=(_); end
  def ruby_version; end
  def ruby_version=(_); end
  def rubygems_version; end
  def rubygems_version=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def to_line; end
end
class CompactIndex::Dependency < Struct
  def checksum; end
  def checksum=(_); end
  def gem; end
  def gem=(_); end
  def platform; end
  def platform=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def version; end
  def version=(_); end
  def version_and_platform; end
end
class CompactIndex::VersionsFile
  def calculate_info_checksums(gems); end
  def contents(gems = nil, args = nil); end
  def create(gems); end
  def created_at_header(path); end
  def gem_lines(gems); end
  def initialize(file = nil); end
  def updated_at; end
end
module CompactIndex
  def self.info(versions); end
  def self.names(gem_names); end
  def self.versions(versions_file, gems = nil, args = nil); end
end
