# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/elasticsearch-rails/all/elasticsearch-rails.rbi
#
# elasticsearch-rails-5.0.2
module Elasticsearch::Rails::Instrumentation::Publishers::SearchRequest
  def execute_with_instrumentation!; end
  def self.included(base); end
end
class Elasticsearch::Rails::Instrumentation::LogSubscriber < ActiveSupport::LogSubscriber
  def self.reset_runtime; end
  def self.runtime; end
  def self.runtime=(value); end
end
module Elasticsearch::Rails::Instrumentation::ControllerRuntime
  def append_info_to_payload(payload); end
  def cleanup_view_runtime; end
  def elasticsearch_runtime; end
  def elasticsearch_runtime=(arg0); end
  extend ActiveSupport::Concern
end
module Elasticsearch::Rails::Instrumentation::ControllerRuntime::ClassMethods
  def log_process_action(payload); end
end
