# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/elasticsearch-dsl/all/elasticsearch-dsl.rbi
#
# elasticsearch-dsl-0.1.7
module Elasticsearch::DSL::Utils
  def __camelize(string); end
  extend Elasticsearch::DSL::Utils
end
module Elasticsearch::DSL::Search::BaseComponent
  def initialize(*args, &block); end
  def self.included(base); end
end
module Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  def name(value = nil); end
  def name=(value); end
  def option_methods; end
end
module Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
  def call; end
  def empty?; end
  def name; end
  def to_hash(options = nil); end
end
module Elasticsearch::DSL::Search::BaseCompoundFilterComponent
  def initialize(*args, &block); end
  def self.included(base); end
  include Enumerable
end
module Elasticsearch::DSL::Search::BaseCompoundFilterComponent::InstanceMethods
  def call; end
  def to_hash(options = nil); end
end
module Elasticsearch::DSL::Search::BaseCompoundFilterComponent::EnumerableMethods
  def <<(value); end
  def [](*args); end
  def each(&block); end
  def empty?; end
  def size; end
  def slice(*args); end
end
module Elasticsearch::DSL::Search::BaseCompoundFilterComponent::MethodDelegation
  def method_missing(name, *args, &block); end
end
module Elasticsearch::DSL::Search::BaseAggregationComponent
  def self.included(base); end
end
module Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  def aggregation(*args, &block); end
  def aggregations; end
  def method_missing(name, *args, &block); end
  def to_hash(options = nil); end
end
class Elasticsearch::DSL::Search::Query
  def call; end
  def initialize(*args, &block); end
  def method_missing(name, *args, &block); end
  def to_hash(options = nil); end
end
class Elasticsearch::DSL::Search::Filter
  def call; end
  def initialize(*args, &block); end
  def method_missing(name, *args, &block); end
  def to_hash(options = nil); end
end
class Elasticsearch::DSL::Search::AggregationsCollection < Hash
  def to_hash; end
end
class Elasticsearch::DSL::Search::Aggregation
  def aggregation(*args, &block); end
  def aggregations; end
  def call; end
  def initialize(*args, &block); end
  def method_missing(name, *args, &block); end
  def to_hash(options = nil); end
end
class Elasticsearch::DSL::Search::Highlight
  def encoder(value); end
  def encoder=(value); end
  def field(name, options = nil); end
  def fields(value_or_name); end
  def initialize(*args, &block); end
  def post_tags(*value); end
  def post_tags=(*value); end
  def pre_tags(*value); end
  def pre_tags=(*value); end
  def self.option_method(name, block = nil); end
  def tags_schema(value); end
  def tags_schema=(value); end
  def to_hash; end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Sort
  def by(name, direction = nil); end
  def empty?; end
  def initialize(*args, &block); end
  def self.option_method(name, block = nil); end
  def to_hash; end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Options
  def _source(*args, &block); end
  def empty?; end
  def explain(*args, &block); end
  def fielddata_fields(*args, &block); end
  def fields(*args, &block); end
  def indices_boost(*args, &block); end
  def initialize(*args, &block); end
  def min_score(*args, &block); end
  def rescore(*args, &block); end
  def script_fields(*args, &block); end
  def source(*args, &block); end
  def to_hash(options = nil); end
  def track_scores(*args, &block); end
  def version(*args, &block); end
end
class Elasticsearch::DSL::Search::Suggest
  def initialize(key, options = nil, &block); end
  def self.option_method(name, block = nil); end
  def to_hash; end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::Match
  def analyzer(*args); end
  def boost(*args); end
  def cutoff_frequency(*args); end
  def fuzziness(*args); end
  def fuzzy_rewrite(*args); end
  def lenient(*args); end
  def max_expansions(*args); end
  def minimum_should_match(*args); end
  def operator(*args); end
  def prefix_length(*args); end
  def query(*args); end
  def self.option_method(name, block = nil); end
  def type(*args); end
  def zero_terms_query(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::Bool
  def boost(*args); end
  def filter(*args, &block); end
  def minimum_should_match(*args); end
  def must(*args, &block); end
  def must_not(*args, &block); end
  def self.option_method(name, block = nil); end
  def should(*args, &block); end
  def to_hash; end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::TopChildren
  def _scope(*args); end
  def factor(*args); end
  def incremental_factor(*args); end
  def query(*args, &block); end
  def score(*args); end
  def self.option_method(name, block = nil); end
  def to_hash; end
  def type(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::Nested
  def inner_hits(*args); end
  def path(*args); end
  def query(*args, &block); end
  def score_mode(*args); end
  def self.option_method(name, block = nil); end
  def to_hash; end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::SpanTerm
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::MoreLikeThis
  def analyzer(*args); end
  def boost(*args); end
  def boost_terms(*args); end
  def docs(*args); end
  def exclude(*args); end
  def fields(*args); end
  def ids(*args); end
  def include(*args); end
  def like(*args); end
  def like_text(*args); end
  def max_doc_freq(*args); end
  def max_query_terms(*args); end
  def max_word_length(*args); end
  def min_doc_freq(*args); end
  def min_term_freq(*args); end
  def min_word_length(*args); end
  def percent_terms_to_match(*args); end
  def self.option_method(name, block = nil); end
  def stop_words(*args); end
  def unlike(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::Common
  def analyzer(*args); end
  def boost(*args); end
  def cutoff_frequency(*args); end
  def disable_coord(*args); end
  def low_freq_operator(*args); end
  def minimum_should_match(*args); end
  def query(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::SpanOr
  def clauses(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::SpanMulti
  def match(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::HasChild
  def inner_hits(*args); end
  def max_children(*args); end
  def min_children(*args); end
  def query(*args, &block); end
  def score_mode(*args); end
  def self.option_method(name, block = nil); end
  def to_hash; end
  def type(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::MatchPhrase
  def analyzer(*args); end
  def boost(*args); end
  def query(*args); end
  def self.option_method(name, block = nil); end
  def slop(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::SpanNot
  def dist(*args); end
  def exclude(*args); end
  def include(*args); end
  def post(*args); end
  def pre(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::FuzzyLikeThisField
  def analyzer(*args); end
  def boost(*args); end
  def fuzziness(*args); end
  def ignore_tf(*args); end
  def like_text(*args); end
  def max_query_terms(*args); end
  def prefix_length(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::Terms
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::SimpleQueryString
  def all_fields(*args); end
  def analyze_wildcard(*args); end
  def analyzer(*args); end
  def default_operator(*args); end
  def fields(*args); end
  def flags(*args); end
  def lenient(*args); end
  def minimum_should_match(*args); end
  def query(*args); end
  def quote_field_suffix(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::MatchAll
  def boost(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::MatchPhrasePrefix
  def boost(*args); end
  def max_expansions(*args); end
  def query(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::FunctionScore
  def boost(*args); end
  def boost_mode(*args); end
  def filter(*args, &block); end
  def functions(value = nil); end
  def functions=(value); end
  def initialize(*args, &block); end
  def max_boost(*args); end
  def query(*args, &block); end
  def score_mode(*args); end
  def script_score(*args); end
  def self.option_method(name, block = nil); end
  def to_hash; end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::Ids
  def self.option_method(name, block = nil); end
  def type(*args); end
  def values(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::Indices
  def indices(*args); end
  def no_match_query(*args); end
  def query(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::QueryString
  def allow_leading_wildcard(*args); end
  def analyze_wildcard(*args); end
  def analyzer(*args); end
  def auto_generate_phrase_queries(*args); end
  def boost(*args); end
  def default_field(*args); end
  def default_operator(*args); end
  def enable_position_increments(*args); end
  def fields(*args); end
  def fuzziness(*args); end
  def fuzzy_max_expansions(*args); end
  def fuzzy_prefix_length(*args); end
  def lenient(*args); end
  def locale(*args); end
  def lowercase_expanded_terms(*args); end
  def minimum_should_match(*args); end
  def phrase_slop(*args); end
  def query(*args); end
  def self.option_method(name, block = nil); end
  def tie_breaker(*args); end
  def time_zone(*args); end
  def type(*args); end
  def use_dis_max(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::MultiMatch
  def analyzer(*args); end
  def boost(*args); end
  def cutoff_frequency(*args); end
  def fields(*args); end
  def fuzziness(*args); end
  def max_expansions(*args); end
  def minimum_should_match(*args); end
  def operator(*args); end
  def prefix_length(*args); end
  def query(*args); end
  def rewrite(*args); end
  def self.option_method(name, block = nil); end
  def slop(*args); end
  def type(*args); end
  def use_dis_max(*args); end
  def zero_terms_query(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::Term
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::Prefix
  def boost(*args); end
  def self.option_method(name, block = nil); end
  def value(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::SpanFirst
  def match(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::Boosting
  def negative(*args); end
  def negative_boost(*args); end
  def positive(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::DisMax
  def boost(*args); end
  def queries(*args); end
  def self.option_method(name, block = nil); end
  def tie_breaker(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::Regexp
  def boost(*args); end
  def flags(*args); end
  def self.option_method(name, block = nil); end
  def value(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::FuzzyLikeThis
  def analyzer(*args); end
  def boost(*args); end
  def fields(*args); end
  def fuzziness(*args); end
  def ignore_tf(*args); end
  def like_text(*args); end
  def max_query_terms(*args); end
  def prefix_length(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::Template
  def params(*args); end
  def query(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::Wildcard
  def boost(*args); end
  def self.option_method(name, block = nil); end
  def value(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::SpanNear
  def collect_payloads(*args); end
  def in_order(*args); end
  def self.option_method(name, block = nil); end
  def slop(*args); end
  def span_near(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::HasParent
  def inner_hits(*args); end
  def parent_type(*args); end
  def query(*args, &block); end
  def score_mode(*args); end
  def self.option_method(name, block = nil); end
  def to_hash; end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::GeoShape
  def indexed_shape(*args); end
  def self.option_method(name, block = nil); end
  def shape(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::ConstantScore
  def boost(*args); end
  def filter(*args, &block); end
  def query(*args, &block); end
  def self.option_method(name, block = nil); end
  def to_hash; end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::Filtered
  def filter(*args, &block); end
  def query(*args, &block); end
  def self.option_method(name, block = nil); end
  def strategy(*args); end
  def to_hash; end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::Exists
  def field(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::Range
  def boost(*args); end
  def format(*args); end
  def gt(*args); end
  def gte(*args); end
  def lt(*args); end
  def lte(*args); end
  def self.option_method(name, block = nil); end
  def time_zone(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Queries::Fuzzy
  def boost(*args); end
  def fuzziness(*args); end
  def max_expansions(*args); end
  def prefix_length(*args); end
  def self.option_method(name, block = nil); end
  def value(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::Bool
  def must(*args, &block); end
  def must_not(*args, &block); end
  def self.option_method(name, block = nil); end
  def should(*args, &block); end
  def to_hash; end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::Not
  def method_missing(name, *args, &block); end
  def self.option_method(name, block = nil); end
  def to_hash(options = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::GeoBoundingBox
  def bottom(*args); end
  def bottom_left(*args); end
  def bottom_right(*args); end
  def left(*args); end
  def right(*args); end
  def self.option_method(name, block = nil); end
  def top(*args); end
  def top_left(*args); end
  def top_right(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::Nested
  def filter(*args, &block); end
  def path(*args); end
  def query(*args, &block); end
  def self.option_method(name, block = nil); end
  def to_hash; end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::Limit
  def self.option_method(name, block = nil); end
  def value(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::GeoPolygon
  def points(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::Missing
  def existence(*args); end
  def field(*args); end
  def null_value(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::HasChild
  def filter(*args, &block); end
  def inner_hits(*args); end
  def max_children(*args); end
  def min_children(*args); end
  def query(*args, &block); end
  def self.option_method(name, block = nil); end
  def to_hash; end
  def type(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::Script
  def params(*args); end
  def script(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::Terms
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::MatchAll
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::GeohashCell
  def initialize(*args, &block); end
  def lat(*args); end
  def lon(*args); end
  def neighbors(*args); end
  def precision(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::Query
  def initialize(*args, &block); end
  def self.option_method(name, block = nil); end
  def to_hash; end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::Or
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseCompoundFilterComponent
  include Elasticsearch::DSL::Search::BaseCompoundFilterComponent::EnumerableMethods
  include Elasticsearch::DSL::Search::BaseCompoundFilterComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseCompoundFilterComponent::MethodDelegation
end
class Elasticsearch::DSL::Search::Filters::Ids
  def self.option_method(name, block = nil); end
  def type(*args); end
  def values(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::Indices
  def filter(*args, &block); end
  def indices(*args); end
  def no_match_filter(*args, &block); end
  def self.option_method(name, block = nil); end
  def to_hash; end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::Term
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::GeoDistance
  def distance(*args); end
  def distance_type(*args); end
  def initialize(*args, &block); end
  def lat(*args); end
  def lon(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::GeoDistanceRange
  def lat(*args); end
  def lon(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::Prefix
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::Regexp
  def flags(*args); end
  def self.option_method(name, block = nil); end
  def value(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::Type
  def self.option_method(name, block = nil); end
  def value(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::HasParent
  def filter(*args, &block); end
  def inner_hits(*args); end
  def parent_type(*args); end
  def query(*args, &block); end
  def score_mode(*args); end
  def self.option_method(name, block = nil); end
  def to_hash; end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::GeoShape
  def indexed_shape(*args); end
  def self.option_method(name, block = nil); end
  def shape(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::Exists
  def field(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Filters::And
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseCompoundFilterComponent
  include Elasticsearch::DSL::Search::BaseCompoundFilterComponent::EnumerableMethods
  include Elasticsearch::DSL::Search::BaseCompoundFilterComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseCompoundFilterComponent::MethodDelegation
end
class Elasticsearch::DSL::Search::Filters::Range
  def boost(*args); end
  def format(*args); end
  def gt(*args); end
  def gte(*args); end
  def lt(*args); end
  def lte(*args); end
  def self.option_method(name, block = nil); end
  def time_zone(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::Filter
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::ReverseNested
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::ValueCount
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::Global
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::Nested
  def path(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::DateRange
  def field(*args); end
  def format(*args); end
  def ranges(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::Stats
  def field(*args); end
  def script(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::Missing
  def field(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::Avg
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::Percentiles
  def compression(*args); end
  def field(*args); end
  def params(*args); end
  def percents(*args); end
  def script(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::IpRange
  def field(*args); end
  def ranges(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::Sum
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::Derivative
  def buckets_path(*args); end
  def format(*args); end
  def gap_policy(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::SerialDiff
  def buckets_path(*args); end
  def format(*args); end
  def gap_policy(*args); end
  def lag(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::SumBucket
  def buckets_path(*args); end
  def format(*args); end
  def gap_policy(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::MovingAvg
  def buckets_path(*args); end
  def format(*args); end
  def gap_policy(*args); end
  def minimize(*args); end
  def model(*args); end
  def self.option_method(name, block = nil); end
  def settings(*args); end
  def window(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::AvgBucket
  def buckets_path(*args); end
  def format(*args); end
  def gap_policy(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::BucketSelector
  def buckets_path(*args); end
  def gap_policy(*args); end
  def script(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::StatsBucket
  def buckets_path(*args); end
  def format(*args); end
  def gap_policy(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::MaxBucket
  def buckets_path(*args); end
  def format(*args); end
  def gap_policy(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::ExtendedStatsBucket
  def buckets_path(*args); end
  def format(*args); end
  def gap_policy(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::CumulativeSum
  def buckets_path(*args); end
  def format(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::PercentilesBucket
  def buckets_path(*args); end
  def format(*args); end
  def gap_policy(*args); end
  def percents(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::BucketScript
  def buckets_path(*args); end
  def format(*args); end
  def gap_policy(*args); end
  def script(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::MinBucket
  def buckets_path(*args); end
  def format(*args); end
  def gap_policy(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::Terms
  def exclude(*args); end
  def field(*args); end
  def include(*args); end
  def min_doc_count(*args); end
  def order(*args); end
  def script(*args); end
  def self.option_method(name, block = nil); end
  def shard_min_doc_count(*args); end
  def shard_size(*args); end
  def size(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::Max
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::Histogram
  def extended_bounds(*args); end
  def field(*args); end
  def interval(*args); end
  def keyed(*args); end
  def min_doc_count(*args); end
  def order(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::ScriptedMetric
  def combine_script(*args); end
  def init_script(*args); end
  def lang(*args); end
  def map_script(*args); end
  def params(*args); end
  def reduce_script(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::Cardinality
  def field(*args); end
  def params(*args); end
  def precision_threshold(*args); end
  def rehash(*args); end
  def script(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::PercentileRanks
  def compression(*args); end
  def field(*args); end
  def params(*args); end
  def script(*args); end
  def self.option_method(name, block = nil); end
  def values(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::Min
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::GeohashGrid
  def field(*args); end
  def precision(*args); end
  def self.option_method(name, block = nil); end
  def shard_size(*args); end
  def size(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::GeoDistance
  def distance_type(*args); end
  def field(*args); end
  def origin(*args); end
  def ranges(*args); end
  def self.option_method(name, block = nil); end
  def unit(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::Filters
  def filters(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::SignificantTerms
  def background_filter(*args); end
  def chi_square(*args); end
  def exclude(*args); end
  def field(*args); end
  def gnd(*args); end
  def include(*args); end
  def min_doc_count(*args); end
  def mutual_information(*args); end
  def self.option_method(name, block = nil); end
  def shard_min_doc_count(*args); end
  def shard_size(*args); end
  def size(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::TopHits
  def from(*args); end
  def self.option_method(name, block = nil); end
  def size(*args); end
  def sort(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::Children
  def self.option_method(name, block = nil); end
  def type(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::ExtendedStats
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::DateHistogram
  def extended_bounds(*args); end
  def field(*args); end
  def format(*args); end
  def interval(*args); end
  def min_doc_count(*args); end
  def order(*args); end
  def post_offset(*args); end
  def post_zone(*args); end
  def pre_offset(*args); end
  def pre_zone(*args); end
  def pre_zone_adjust_large_interval(*args); end
  def self.option_method(name, block = nil); end
  def time_zone(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::GeoBounds
  def field(*args); end
  def self.option_method(name, block = nil); end
  def wrap_longitude(*args); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
class Elasticsearch::DSL::Search::Aggregations::Range
  def field(*args); end
  def key(key, value); end
  def keyed(*args); end
  def params(*args); end
  def script(*args); end
  def self.option_method(name, block = nil); end
  extend Elasticsearch::DSL::Search::BaseComponent::ClassMethods
  include Elasticsearch::DSL::Search::BaseAggregationComponent
  include Elasticsearch::DSL::Search::BaseAggregationComponent::InstanceMethods
  include Elasticsearch::DSL::Search::BaseComponent
  include Elasticsearch::DSL::Search::BaseComponent::InstanceMethods
end
module Elasticsearch::DSL::Search
  def search(*args, &block); end
  extend Elasticsearch::DSL::Search
end
class Elasticsearch::DSL::Search::Search
  def aggregation(*args, &block); end
  def aggregations; end
  def aggregations=(value); end
  def filter(*args, &block); end
  def filter=(value); end
  def from(value = nil); end
  def from=(value = nil); end
  def highlight(*args, &block); end
  def initialize(*args, &block); end
  def method_missing(name, *args, &block); end
  def post_filter(*args, &block); end
  def post_filter=(value); end
  def query(*args, &block); end
  def query=(value); end
  def size(value = nil); end
  def size=(value = nil); end
  def sort(*args, &block); end
  def stored_fields(value = nil); end
  def stored_fields=(value = nil); end
  def suggest(*args, &block); end
  def suggest=(value); end
  def to_hash; end
end
module Elasticsearch::DSL
  def self.included(base); end
end
