# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/gravtastic/all/gravtastic.rbi
#
# gravtastic-3.2.6
module Gravtastic
  def self.configure(model, *args, &blk); end
  def self.included(model); end
  def self.version; end
end
module Gravtastic::StageOne
  def gravtastic!(*args, &blk); end
  def gravtastic(*args, &blk); end
  def has_gravatar(*args, &blk); end
  def is_gravtastic!(*args, &blk); end
  def is_gravtastic(*args, &blk); end
end
module Gravtastic::ClassMethods
  def gravatar_abbreviations; end
  def gravatar_defaults; end
  def gravatar_defaults=(arg0); end
  def gravatar_source; end
  def gravatar_source=(arg0); end
end
module Gravtastic::InstanceMethods
  def gravatar_filename(filetype); end
  def gravatar_hostname(secure); end
  def gravatar_id; end
  def gravatar_url(options = nil); end
  def url_params_from_hash(hash); end
end
