# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/high_voltage/all/high_voltage.rbi
#
# high_voltage-3.1.0
module HighVoltage::Configuration
  def configure; end
  def content_path; end
  def content_path=(arg0); end
  def full_path; end
  def home_page; end
  def home_page=(arg0); end
  def layout; end
  def layout=(arg0); end
  def page_ids; end
  def parent_engine; end
  def parent_engine=(arg0); end
  def route_drawer; end
  def route_drawer=(arg0); end
  def routes; end
  def routes=(arg0); end
  def self.extended(base); end
  def set_default_configuration; end
end
class HighVoltage::Constraints::RootRoute
  def clean_page_path(request_path); end
  def content_path; end
  def initialize; end
  def lookup_context; end
  def matches?(request); end
end
class HighVoltage::Page
  def available_handlers; end
  def content_path; end
  def directory?; end
  def exists?; end
  def file_in_content_path?; end
  def file_path; end
  def handled?; end
  def handler_extension; end
  def id; end
  def initialize(content_path, file_path); end
  def partial?; end
  def valid?; end
end
class HighVoltage::PageCollector
  def content_path; end
  def initialize(content_path); end
  def page_ids; end
  def pages; end
end
class HighVoltage::PageFinder
  def clean_content_pathname; end
  def content_path; end
  def find; end
  def initialize(page_id); end
  def page_id; end
end
class HighVoltage::RouteDrawers::Default
  def self.match_attributes; end
end
class HighVoltage::RouteDrawers::Root
  def self.match_attributes; end
end
module HighVoltage
  extend HighVoltage::Configuration
end
