# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/logstash-event/all/logstash-event.rbi
#
# logstash-event-1.2.02
module LogStash::Util
  def self.hash_merge(dst, src); end
  def self.hash_merge_many(*hashes); end
  def self.hash_merge_with_dups(dst, src); end
  def self.set_thread_name(name); end
end
module LogStash::Util::FieldReference
  def compile(str); end
  def exec(str, obj, &block); end
  extend LogStash::Util::FieldReference
end
class Time
  def to_json(*args); end
end
class LogStash::Event
  def [](str); end
  def []=(str, value); end
  def append(event); end
  def cancel; end
  def cancelled?; end
  def clone; end
  def fields; end
  def include?(key); end
  def initialize(data = nil); end
  def message=(value); end
  def overwrite(event); end
  def remove(str); end
  def ruby_timestamp; end
  def self.included(klass); end
  def source=(value); end
  def sprintf(format); end
  def tag(value); end
  def tags; end
  def tags=(value); end
  def timestamp; end
  def timestamp=(val); end
  def to_hash; end
  def to_json(*args); end
  def to_s; end
  def type; end
  def type=(value); end
  def uncancel; end
  def unix_timestamp; end
end
module LogStash::Event::ClassMethods
  def from_json(json); end
end
