# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rack-utf8_sanitizer/all/rack-utf8_sanitizer.rbi
#
# rack-utf8_sanitizer-1.6.0
class Rack::UTF8Sanitizer
  def build_strategy(options); end
  def call(env); end
  def decode_string(input); end
  def escape_unreserved(input); end
  def initialize(app, options = nil); end
  def reencode_string(decoded_value); end
  def sanitize(env); end
  def sanitize_cookies(env); end
  def sanitize_io(io, uri_encoded = nil); end
  def sanitize_rack_input(env); end
  def sanitize_string(input); end
  def sanitize_uri_encoded_string(input); end
  def skip?(rack_env_key); end
  def strip_byte_order_mark(input); end
  def transfer_frozen(from, to); end
  def unescape_unreserved(input); end
end
class Rack::UTF8Sanitizer::SanitizedRackInput
  def close; end
  def each(&block); end
  def gets; end
  def initialize(original_io, sanitized_io); end
  def read(*args); end
  def rewind; end
  def size; end
end
