# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/validates_formatting_of/all/validates_formatting_of.rbi
#
# validates_formatting_of-0.9.0
class ValidatesFormattingOf::InvalidRegularExpression < StandardError
  def initialize(name); end
end
class ValidatesFormattingOf::Validation
  def initialize(name, regexp, message = nil); end
  def inspect; end
  def message; end
  def name; end
  def regex; end
  def to_s; end
end
class ValidatesFormattingOf::MissingValidation < StandardError
  def initialize(method); end
end
module ValidatesFormattingOf::ValidationAddition
  def add(name, regex, message = nil); end
  def exists?(name); end
  def find(attribute, opts = nil); end
  def missing?(name); end
  def validations; end
end
module ValidatesFormattingOf::Method
  extend ValidatesFormattingOf::ValidationAddition
end
class ValidatesFormattingOf::Validations::Validator < ActiveModel::Validations::FormatValidator
  def initialize(options = nil, format = nil); end
end
class ValidatesFormattingOf::Validations::EmailValidator < ValidatesFormattingOf::Validations::Validator
  def initialize(options = nil); end
end
class ValidatesFormattingOf::Validations::SimpleEmailValidator < ValidatesFormattingOf::Validations::Validator
  def initialize(options = nil); end
end
class ValidatesFormattingOf::Validations::UrlValidator < ValidatesFormattingOf::Validations::Validator
  def initialize(options = nil); end
end
class ValidatesFormattingOf::Validations::AlphaValidator < ValidatesFormattingOf::Validations::Validator
  def initialize(options = nil); end
end
class ValidatesFormattingOf::Validations::AlphanumValidator < ValidatesFormattingOf::Validations::Validator
  def initialize(options = nil); end
end
class ValidatesFormattingOf::Validations::CreditCardValidator < ValidatesFormattingOf::Validations::Validator
  def initialize(options = nil); end
end
class ValidatesFormattingOf::Validations::UsZipValidator < ValidatesFormattingOf::Validations::Validator
  def initialize(options = nil); end
end
class ValidatesFormattingOf::Validations::UsPhoneValidator < ValidatesFormattingOf::Validations::Validator
  def initialize(options = nil); end
end
class ValidatesFormattingOf::Validations::IpAddressV4Validator < ValidatesFormattingOf::Validations::Validator
  def initialize(options = nil); end
end
class ValidatesFormattingOf::Validations::SsnValidator < ValidatesFormattingOf::Validations::Validator
  def initialize(options = nil); end
end
class ValidatesFormattingOf::Validations::HexColorValidator < ValidatesFormattingOf::Validations::Validator
  def initialize(options = nil); end
end
class ValidatesFormattingOf::Validations::DollarsValidator < ValidatesFormattingOf::Validations::Validator
  def initialize(options = nil); end
end
module ValidatesFormattingOf::ModelAdditions
  def validates_formatting_of(attribute, options = nil); end
end
