# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_10; end
module ::Anonymous_Delegator_11; end
module ::Anonymous_Delegator_12; end
module ::Anonymous_Delegator_14; end
module ::Anonymous_Delegator_2; end
module ::Anonymous_Delegator_20; end
module Aws::S3::Errors::NoSuchKey; end
module Aws::S3::Errors::NoSuchKey; end
module RuboCop::Cop::Cop; end
module Rubygem::NAME_PATTERN; end
